# Generated by Django 2.2.6 on 2019-10-16 22:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('text_show', models.CharField(max_length=100)),
                ('show_on_menu', models.BooleanField(default=True)),
                ('order', models.IntegerField(blank=True, default=0)),
                ('template', models.CharField(blank=True, help_text='If present, use this template instead the standard one', max_length=50)),
                ('user_is_logged', models.BooleanField(default=False, help_text='Only display this entry if the user is logged in.')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=300, null=True)),
                ('card_body', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('teaser_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('content_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('order', models.IntegerField(blank=True, default=0)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('read_more', models.BooleanField(default=False)),
                ('alternate_target_url', models.CharField(blank=True, help_text='If present, detail button will direct to destination, instead of content detail.', max_length=50)),
                ('alternate_read_more_label', models.CharField(blank=True, help_text="If present, will display on 'read more' button.", max_length=50)),
                ('publish_date', models.DateField(default=datetime.datetime.now)),
                ('template', models.CharField(blank=True, help_text='If present, use this template instead the standard one', max_length=50)),
                ('user_is_logged', models.BooleanField(default=False, help_text='Only display this entry if the user is logged in.')),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ContentCategory')),
            ],
        ),
    ]
